services:
  postgres-payment:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5434:5432"
    volumes:
      - postgres-payment_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME_PAYMENT}
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5

  postgres-order:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres-order_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME_ORDER}
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5

  postgres-warehouse:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5433:5432"
    volumes:
      - postgres-warehouse_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME_WAREHOUSE}
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    restart: unless-stopped
    ports:
      - "29092:29092"
      - "9092:9092"
    volumes:
      - kafka_data:/var/lib/kafka/data
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_NODE_ID: 1
      CLUSTER_ID: e3QcjBLhR9Giv_NA0FmB5A
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://0.0.0.0:9092,CONTROLLER://kafka:9093
    healthcheck:
      test: kafka-topics --bootstrap-server localhost:9092 --list
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 5
    labels:
      amplicode.image: confluent/kafka

  order-platform.order-service:
    image: order-platform.order-service:latest
    build:
      context: .
      dockerfile: order-service/Dockerfile
    restart: unless-stopped
    ports:
      - "${PORT_ORDER}:8080"

    environment:
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-order:5432/${DB_NAME_ORDER}
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:29092
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/ || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
    depends_on:
      postgres-order:
          condition: service_healthy
      kafka:
        condition: service_healthy
    labels:
      amplicode.image: springboot

  order-platform.payment-service:
    image: order-platform.payment-service:latest
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    restart: unless-stopped
    ports:
      - "${PORT_PAYMENT}:8081"
    environment:
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-payment:5432/${DB_NAME_PAYMENT}
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:29092
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8081/ || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
    depends_on:
      postgres-payment:
        condition: service_healthy
      kafka:
        condition: service_healthy
    labels:
      amplicode.image: springboot

  order-platform.warehouse-service:
    image: order-platform.warehouse-service:latest
    build:
      context: .
      dockerfile: warehouse-service/Dockerfile
    restart: unless-stopped
    ports:
      - "${PORT_WAREHOUSE}:8083"

    environment:
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-warehouse:5432/${DB_NAME_WAREHOUSE}
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:29092
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8083/ || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
    depends_on:
        postgres-warehouse:
          condition: service_healthy
        kafka:
          condition: service_healthy
    labels:
      amplicode.image: springboot






volumes:
  postgres-order_data:
  kafka_data:
  postgres-warehouse_data:
  postgres-payment_data: